# Name: Swarm Metaheuristic with Levy Distribution

# Code:
import sys
from pathlib import Path

project_dir = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_dir))
import benchmark_func as bf
import metaheuristic as mh

fun = bf.Rastrigin(2)   
prob = fun.get_formatted_problem()

heur = [
    (
        'swarm_dynamic',
        {
            'factor': 0.7,
            'self_conf': 2.54,
            'swarm_conf': 2.56,
            'version': 'inertial',
            'distribution': 'levy'
        },
        'probabilistic'
    )
]

met = mh.Metaheuristic(prob, heur, num_iterations=100)
met.verbose = True
met.run()

print('x_best = {}, f_best = {}'.format(*met.get_solution()))

# Short explanation and justification:
# We chose the swarm_dynamic operator with the Levy distribution as it has been shown to perform well in optimization problems with complex non-linear landscapes.
# The probabilistic selector was chosen to guide the swarm based on the probability distribution generated by the Levy distribution.
# The factor parameter controls the influence of the swarm and the self-confidence on the probability distribution.
# The swarm-confidence and self-confidence parameters determine the influence of the swarm and the individual on the probability distribution.
# The inertial version of the swarm dynamics provides a smooth transition between the swarm and individual movements.